# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: project_environment
channels:
  - defaults
dependencies:
  - python=3.6.8
  - r-reticulate
  - r=3.5.0
  - r-car
  - pip:
    - azureml-defaults==1.19
    - pandas
    - pyarrow
